[package]
name = "betfair_trader"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.9", features = ["rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
pkcs8 = { version = "0.10.2", features = ["pkcs5"] }

toml = "0.8"
rand = "0.9"
rustls = "0.23" 
rustls-pemfile = "2.2"
pem = "3.0"
serde_json = "1.0"
anyhow = "1.0"
dotenv = "0.15"
chrono = "0.4"
